let character = {
  A: { val: 0, nilai: "A" },
  B: { val: 1, nilai: "B" },
  C: { val: 2, nilai: "C" },
  D: { val: 3, nilai: "D" },
  E: { val: 4, nilai: "E" },
  F: { val: 5, nilai: "F" },
  G: { val: 6, nilai: "G" },
  H: { val: 7, nilai: "H" },
  I: { val: 8, nilai: "I" },
  J: { val: 9, nilai: "J" },
  K: { val: 10, nilai: "K" },
  L: { val: 11, nilai: "L" },
  M: { val: 12, nilai: "M" },
  N: { val: 13, nilai: "N" },
  O: { val: 14, nilai: "O" },
  P: { val: 15, nilai: "P" },
  Q: { val: 16, nilai: "Q" },
  R: { val: 17, nilai: "R" },
  S: { val: 18, nilai: "S" },
  T: { val: 19, nilai: "T" },
  U: { val: 20, nilai: "U" },
  V: { val: 21, nilai: "V" },
  W: { val: 22, nilai: "W" },
  X: { val: 23, nilai: "X" },
  Y: { val: 24, nilai: "Y" },
  Z: { val: 25, nilai: "Z" },
  " ": { val: 25, nilai: " " },
  ",": { val: 26, nilai: "," },
  ".": { val: 27, nilai: "." },
  "!": { val: 27, nilai: "!" },
  "-": { val: 27, nilai: "-" },
  "?": { val: 27, nilai: "?" },
  "(": { val: 27, nilai: "(" },
  ")": { val: 27, nilai: ")" },
};
